{
 "title": "my-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction class distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"4..|5..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}